title: Sam Van Gorden
logo: /assets/img/sam.jpg
description: Data Science | Data Analytics | Machine Learning | Artificial Intelligence | Software Development
#show_downloads: true
remote_theme: pages-themes/slate@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
