title: Sam Van Gorden
logo: /assets/img/sam.jpg
description: Data Science | Data Analytics | Machine Learning | Artificial Intelligence | Software Development
#show_downloads: true
remote_theme: jekyll-theme-slate

github:
  is_project_page: false
